spring:
  rabbitmq:
    host: 127.0.0.1
    username: user01
    password: 123
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 2
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    virtual-host: /test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    lettuce:
      shutdown-timeout: 0
    timeout: 1200